### ISSUE TITLE
Fix: ver3 이후로 발생하는 오류 작업용 이슈

### ISSUE THREAD

**Issue by Seong-Myeong** [baeksaitong/SOFP_FRONT#126]
## 📌 F Issue

* 카메라 재촬영 부분에서 재촬영시 사진이 촬영만 구현됨
* 캘린더 UI 오류 수정

## 📝 To-do
- [x] 카메라 재촬영하기 검색 안되던 현상 수정
- [x] 캘린더 UI ( 상세 일정 보기 하단시트로 변경 )
- [x] 프로필 정보 수정 페이지 에셋 사라지는 현상 수정
- [x] 프로필 정보 수정 페이지 색 추가 버튼 되찾기
- [x] 멀티프로필 버튼 연결 

## 💡 ETC

>
